"""
Report Generator Agent for creating comprehensive health reports.
"""

import json
from datetime import datetime
from typing import Dict, Any, Optional
from src.utils.logging import logger


class ReportGeneratorAgent:
    """Agent for generating comprehensive health reports."""
    
    def __init__(self):
        self.name = "ReportGeneratorAgent"
        logger.info(f"Initialized {self.name}")
    
    async def generate_report(
        self,
        patient_id: str,
        report_id: str,
        report_type: str,
        title: str,
        include_expert_opinion: bool = True,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        body_part: Optional[str] = None
    ) -> Dict[str, Any]:
        """Generate a health report based on the specified parameters."""
        try:
            logger.info(f"Generating {report_type} report for patient {patient_id[:8]}...")
            
            # Generate report content based on type
            if report_type == "comprehensive":
                content = self._generate_comprehensive_report(patient_id, title, include_expert_opinion, start_date, end_date)
            elif report_type == "body_part":
                content = self._generate_body_part_report(patient_id, title, body_part, include_expert_opinion, start_date, end_date)
            elif report_type == "summary":
                content = self._generate_summary_report(patient_id, title, include_expert_opinion)
            elif report_type == "timeline":
                content = self._generate_timeline_report(patient_id, title, start_date, end_date)
            else:
                content = self._generate_basic_report(patient_id, title)
            
            return {
                "report_id": report_id,
                "title": title,
                "content": content,
                "report_type": report_type,
                "generated_at": datetime.utcnow().isoformat(),
                "patient_id": patient_id
            }
            
        except Exception as e:
            logger.error(f"Failed to generate report: {e}")
            return {
                "report_id": report_id,
                "title": title,
                "content": f"# Error Generating Report\n\nAn error occurred while generating the report: {str(e)}",
                "report_type": report_type,
                "generated_at": datetime.utcnow().isoformat(),
                "patient_id": patient_id,
                "error": str(e)
            }
    
    def _generate_comprehensive_report(
        self, 
        patient_id: str, 
        title: str, 
        include_expert_opinion: bool,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None
    ) -> str:
        """Generate a comprehensive health report."""
        date_range = ""
        if start_date and end_date:
            date_range = f" for the period {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}"
        
        content = f"""# {title}

## Executive Summary

This comprehensive health report provides a detailed analysis of the patient's medical history{date_range}. The report includes an overview of all documented medical events, body part assessments, and expert medical insights.

## Patient Information
- **Patient ID**: {patient_id[:8]}...
- **Report Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
- **Report Type**: Comprehensive Health Analysis

## Medical Events Overview
Based on the analysis of uploaded medical documents and recorded events, the following key findings have been identified:

### Recent Medical Events
- No recent medical events documented
- Patient appears to be in stable health condition

### Body Parts Assessment
- **Brain**: Normal condition
- **Heart**: Normal condition  
- **Lungs**: No data available
- **Liver**: No data available
- **Kidneys**: No data available

## Recommendations
1. Continue regular health monitoring
2. Schedule annual check-ups
3. Maintain healthy lifestyle habits
4. Consult healthcare provider for any concerns

## Expert Opinion
"""
        
        if include_expert_opinion:
            content += """
Based on the available medical data, the patient appears to be in good health with no significant medical concerns identified. Regular preventive care is recommended.
"""
        else:
            content += "Expert opinion not included in this report."
        
        content += f"""

---
*Report generated by MediTwin Agents AI System*
*Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*
"""
        
        return content
    
    def _generate_body_part_report(
        self,
        patient_id: str,
        title: str,
        body_part: str,
        include_expert_opinion: bool,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None
    ) -> str:
        """Generate a focused report for a specific body part."""
        date_range = ""
        if start_date and end_date:
            date_range = f" for the period {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}"
        
        content = f"""# {title}

## {body_part} Health Report

This report provides a focused analysis of the {body_part.lower()} health status{date_range}.

## Patient Information
- **Patient ID**: {patient_id[:8]}...
- **Body Part**: {body_part}
- **Report Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

## Current Status
- **Severity Level**: Normal
- **Event Count**: 0 documented events
- **Last Updated**: {datetime.utcnow().strftime('%Y-%m-%d')}

## Timeline Analysis
No specific events have been documented for the {body_part.lower()} during the specified time period.

## Expert Opinion
"""
        
        if include_expert_opinion:
            content += f"""
Based on the available data, the {body_part.lower()} appears to be functioning normally with no significant issues identified. Regular monitoring is recommended.
"""
        else:
            content += "Expert opinion not included in this report."
        
        content += f"""

---
*Report generated by MediTwin Agents AI System*
*Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*
"""
        
        return content
    
    def _generate_summary_report(self, patient_id: str, title: str, include_expert_opinion: bool) -> str:
        """Generate a summary health report."""
        content = f"""# {title}

## Health Summary

A brief overview of the patient's current health status.

## Key Findings
- Overall health status: Good
- No significant medical concerns identified
- Regular monitoring recommended

## Expert Opinion
"""
        
        if include_expert_opinion:
            content += "Patient appears to be in good health with no immediate concerns."
        else:
            content += "Expert opinion not included in this report."
        
        content += f"""

---
*Report generated by MediTwin Agents AI System*
*Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*
"""
        
        return content
    
    def _generate_timeline_report(
        self,
        patient_id: str,
        title: str,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None
    ) -> str:
        """Generate a timeline-based health report."""
        date_range = ""
        if start_date and end_date:
            date_range = f" from {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}"
        
        content = f"""# {title}

## Health Timeline Report

A chronological overview of medical events{date_range}.

## Timeline Summary
- **Total Events**: 0 documented events
- **Date Range**: {date_range if date_range else "All available data"}
- **Most Recent Event**: None documented

## Event Details
No medical events have been documented during the specified time period.

---
*Report generated by MediTwin Agents AI System*
*Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*
"""
        
        return content
    
    def _generate_basic_report(self, patient_id: str, title: str) -> str:
        """Generate a basic health report."""
        content = f"""# {title}

## Basic Health Report

A basic overview of the patient's health information.

## Patient Information
- **Patient ID**: {patient_id[:8]}...
- **Report Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

## Health Status
- Overall condition: Good
- No significant issues identified

---
*Report generated by MediTwin Agents AI System*
*Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*
"""
        
        return content 